[package]
name = "openai"
version = "0.1.0"
edition = "2021"

# [lib]
# name = "openai"           # The name of the target.
# path = "src/openai.rs"    # The source file of the target.
# test = true            # Is tested by default.
# doctest = true         # Documentation examples are tested by default.
# bench = true           # Is benchmarked by default.
# doc = true             # Is documented by default.
# plugin = false         # Used as a compiler plugin (deprecated).
# proc-macro = false     # Set to `true` for a proc-macro library.
# harness = true         # Use libtest harness.
# edition = "2021"      # The edition of the target.
# crate-type = ["lib"]   # The crate types to generate.
# required-features = [] # Features required to build this target (N/A for lib).

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
